version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: liquidium_postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=liquidium
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: